---
title: "ggplotintro"
author: "Dan Schofield"
date: "13 July 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Plan 
We'll load libraries and learn ggplot2
Here we write in Mark down

#hashtags mean headers. 

summary(cars)

```{r}
# here we write R

#hashtags mean comment
```

## Load libraries
```{r}
# loading my libraries

library(dplyr)
library(gapminder)
library(ggplot2) # install.packages('ggplot2')

## subset our data 
g <- gapminder %>% 
  filter(year == 2007) %>%
  mutate(pop_m = pop/1e6)
```

# My first plot
a simple geom_point
```{r}
## ggplot(data, aes(what's x, what's y)) + what_kind_of_plot()
s <- ggplot(g, aes(x = gdpPercap, y = lifeExp)) +
  geom_point()
s
```


# My second plot
a simple geom_point with aes()
```{r}
## ggplot(data, aes(what's x, what's y)) + what_kind_of_plot()
s2 = s + aes(size = pop_m)

s2

s3 = s2 + aes(color = continent)
s3 
```


# nice piped!

```{r}
s <- ggplot(g, aes(x = gdpPercap, y = lifeExp)) +
  geom_point() +
  aes(size = pop_m) +
  aes(color = continent) +
  ggtitle('Health and Wealth of Nations for 2007') +
  xlab('GDP per capita (USD/year)') +
  ylab('Life expectency (years)') +
  scale_colour_discrete('Continent') +
  scale_size_continuous('Population (m)')
s
```

## Make a boxplot 

This is my boxplot of continent and life expectency. 
Using `g`, which is a subset of 2007

```{r}
## hint: look the cheatsheet for how to do this

b <- ggplot(g, aes(x = continent, y = lifeExp)) +
  geom_boxplot() +
  aes(fill=continent) +
  theme(legend.position = 'none')
b
```

#lol
# 2olol

